name: External Usage Request
description: Request permission to use San Orien Software outside the San Orien ecosystem.
title: "`[Usage Request]` "
labels:
  - license
  - external-usage-request
  - approval-required
assignees:
  - intensed-dev

body:
  - type: markdown
    attributes:
      value: |
        According to the San Orien General License, external usage requires approval.

  - type: input
    id: project
    attributes:
      label: Project name

  - type: input
    id: repository
    attributes:
      label: Repository URL (optional)

  - type: input
    id: website
    attributes:
      label: Website (optional)

  - type: dropdown
    id: commercial
    attributes:
      label: Commercial?
      options:
        - "Commercial"
        - "Non-Commercial"
        
  - type: dropdown
    id: software
    attributes:
      label: Software you need access to
      options:
        - "All San Orien Software"
        - "San Orien Symbols"
        - "San Orien Font"

  - type: textarea
    id: description
    attributes:
      label: Describe your project

  - type: textarea
    id: usage
    attributes:
      label: How will San Orien Software be used?

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I have read the license.
        - label: I will provide attribution.
        - label: I understand that approval is not guaranteed.
